version: '3.8'

services:
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: cardwebsite
  #     POSTGRES_USER: cardwebsite
  #     POSTGRES_PASSWORD: cardwebsite
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - backend

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 cardWebSite.wsgi:application --workers 4 --timeout 120
    env_file:
      - .env
    environment:
      DJANGO_DEBUG: 'True'
    volumes:
      - .:/app
      - ./static:/app/static
    ports:
      - "8000:8000"
    expose:
      - "8000"
    # depends_on:
    #   - db
    networks:
      - backend

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - backend
volumes:
  # postgres_data:
  static-data:


networks:
  backend:
