version: '3.9'

services:
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend


  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 cardWebSite.wsgi:application
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend

  nginx:
    build: ./nginx
    volumes:
      - static-data:/home/app/web/static
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static-data:

networks:
  backend: