# Generated by Django 5.1 on 2024-08-14 13:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contactinfo_project_resume_delete_websitemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
